import {
  pgTable,
  uuid,
  text,
  timestamp,
  integer,
  date,
  time,
  index,
  uniqueIndex,
} from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import { homeowners } from './homeowners';
import { homeownerProperties } from './homeowner-properties';
import { providers } from './providers';

/**
 * Homie Membership — Phase 1: Recurring Vendors.
 *
 * Three tables modeled together because their lifecycles are tightly
 * coupled:
 *
 *   recurring_vendors  — the homeowner-vendor relationship + schedule
 *   vendor_visits      — one row per scheduled visit, generated by the
 *                        nightly schedule engine (Session 3+ work)
 *   vendor_payments    — one row per payment from member to vendor
 *                        (Session 3 wires this to Stripe Connect)
 *
 * Co-located in one schema file to mirror how
 * `db/schema/inspector.ts` co-locates inspectionReports +
 * inspectionReportItems + inspectionSupportingDocuments. Keeps the
 * vendor-payment lifecycle visible in one place.
 *
 * Note on parallel B2B code: `db/schema/schedules.ts` already has
 * `dispatchSchedules` + `dispatchScheduleRuns` for B2B property
 * managers. We intentionally duplicate the conceptual shape rather
 * than refactoring to a polymorphic owner model — the consumer flow
 * has BYO vendors with SMS confirmation, Stripe Connect payouts, and
 * travel-hold semantics that don't apply to B2B. Unification can be
 * revisited later once both products are stable.
 */

// ─── Allowed-value constants ────────────────────────────────────────────────
//
// Codebase convention is text columns + TS literal-union constants over
// PG-native enums (text is much easier to evolve and matches every other
// status/category column in the codebase). App code is the source of truth
// for what's allowed; a CHECK constraint can be added per-column later if
// invalid writes ever leak in.

export const VENDOR_SERVICE_CATEGORIES = [
  'cleaning',
  'landscaping',
  'pool',
  'pest_control',
  'hvac',
  'window_cleaning',
  'trash_valet',
  'handyman',
  'other',
] as const;
export type VendorServiceCategory = (typeof VENDOR_SERVICE_CATEGORIES)[number];

export const VENDOR_TYPES = ['byo', 'network'] as const;
export type VendorType = (typeof VENDOR_TYPES)[number];

export const VENDOR_SCHEDULE_PATTERNS = [
  'weekly',
  'biweekly_even',
  'biweekly_odd',
  'monthly_date',
  'monthly_nth_day',
  'quarterly',
  'custom',
] as const;
export type VendorSchedulePattern = (typeof VENDOR_SCHEDULE_PATTERNS)[number];

export const VENDOR_PAYMENT_METHODS = ['card', 'ach', 'homie_credit'] as const;
export type VendorPaymentMethod = (typeof VENDOR_PAYMENT_METHODS)[number];

export const VENDOR_AUTO_PAY_RULES = [
  'always',
  'if_under_threshold',
  'manual_approval',
] as const;
export type VendorAutoPayRule = (typeof VENDOR_AUTO_PAY_RULES)[number];

export const RECURRING_VENDOR_STATUSES = [
  'pending_vendor_confirmation',
  'active',
  'paused',
  'travel_hold',
  'cancelled',
] as const;
export type RecurringVendorStatus = (typeof RECURRING_VENDOR_STATUSES)[number];

export const VENDOR_VISIT_STATUSES = [
  'scheduled',
  'confirmation_sent',
  'confirmed',
  'completed',
  'skipped',
  'missed',
  'disputed',
] as const;
export type VendorVisitStatus = (typeof VENDOR_VISIT_STATUSES)[number];

export const VENDOR_PAYMENT_STATUSES = [
  'pending',
  'processing',
  'succeeded',
  'failed',
  'refunded',
] as const;
export type VendorPaymentStatus = (typeof VENDOR_PAYMENT_STATUSES)[number];

// ─── recurring_vendors ──────────────────────────────────────────────────────

export const recurringVendors = pgTable(
  'recurring_vendors',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    homeownerPropertyId: uuid('homeowner_property_id')
      .notNull()
      .references(() => homeownerProperties.id, { onDelete: 'cascade' }),
    homeownerId: uuid('homeowner_id')
      .notNull()
      .references(() => homeowners.id, { onDelete: 'cascade' }),
    vendorName: text('vendor_name').notNull(),
    vendorPhone: text('vendor_phone'),
    vendorEmail: text('vendor_email'),
    /** Allowed values: VENDOR_SERVICE_CATEGORIES. Validated in app code. */
    serviceCategory: text('service_category').notNull(),
    /** Allowed values: VENDOR_TYPES. */
    vendorType: text('vendor_type').notNull(),
    /** Set only when vendorType='network'. ON DELETE SET NULL so removing
     *  a provider from the directory doesn't cascade-delete the homeowner's
     *  recurring relationship — the row converts to a BYO-shaped record
     *  (homeowner can re-link or replace). */
    networkProviderId: uuid('network_provider_id').references(() => providers.id, {
      onDelete: 'set null',
    }),
    /** Allowed values: VENDOR_SCHEDULE_PATTERNS. */
    schedulePattern: text('schedule_pattern').notNull(),
    scheduleDayOfWeek: integer('schedule_day_of_week'),
    scheduleDayOfMonth: integer('schedule_day_of_month'),
    /** "first_tuesday" etc. when schedulePattern='monthly_nth_day'. */
    scheduleNthWeekday: text('schedule_nth_weekday'),
    /** HH:MM[:SS] local time. */
    scheduleTime: time('schedule_time'),
    /** Used when schedulePattern='custom' — explicit list of dates. */
    scheduleCustomDates: date('schedule_custom_dates').array(),
    amountCents: integer('amount_cents').notNull(),
    /** Allowed values: VENDOR_PAYMENT_METHODS. */
    paymentMethod: text('payment_method').notNull(),
    /** Stripe payment-method ID for cards/ACH; null for homie_credit. */
    paymentMethodId: text('payment_method_id'),
    /** Allowed values: VENDOR_AUTO_PAY_RULES. */
    autoPayRule: text('auto_pay_rule').notNull(),
    autoPayThresholdCents: integer('auto_pay_threshold_cents'),
    /** Allowed values: RECURRING_VENDOR_STATUSES. New rows start in
     *  'pending_vendor_confirmation' (vendor hasn't completed Connect
     *  onboarding yet); the SMS confirmation flow flips to 'active'. */
    status: text('status').notNull().default('pending_vendor_confirmation'),
    travelHoldStartsAt: date('travel_hold_starts_at'),
    travelHoldEndsAt: date('travel_hold_ends_at'),
    vendorConfirmedAt: timestamp('vendor_confirmed_at', { withTimezone: true }),
    /** Updated by payment processing each time a payment succeeds.
     *  Reset to 0 on Jan 1 by a yearly job (Session 3+). */
    totalPaidYtdCents: integer('total_paid_ytd_cents').notNull().default(0),
    /** Stripe Connect Express account ID for the vendor. Populated by
     *  the SMS-confirmation flow once the vendor finishes Stripe-hosted
     *  onboarding. Mirrors `inspector_partners.stripe_connect_account_id`
     *  naming. Null until then. */
    stripeConnectAccountId: text('stripe_connect_account_id'),
    /** One-time token used to scope the unauth vendor confirmation
     *  page (`/vendor-confirmation/:token`). Generated when the row is
     *  created and re-rotatable. Cleared when onboarding finishes (so
     *  the link can't be re-used) or after expiry. Unique partial
     *  index ensures at most one live token per vendor. */
    vendorConfirmationToken: text('vendor_confirmation_token'),
    /** When `vendor_confirmation_token` becomes invalid. Spec says 7
     *  days; expired tokens 410 the page and a new one is requested. */
    vendorConfirmationTokenExpiresAt: timestamp('vendor_confirmation_token_expires_at', {
      withTimezone: true,
    }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index('recurring_vendors_property_status_idx').on(
      table.homeownerPropertyId,
      table.status,
    ),
    index('recurring_vendors_homeowner_idx').on(table.homeownerId),
    index('recurring_vendors_network_provider_idx').on(table.networkProviderId),
    index('recurring_vendors_connect_account_idx').on(table.stripeConnectAccountId),
    // Partial unique on the live token so two concurrent confirmation
    // links can't exist for the same vendor (rotation behavior).
    uniqueIndex('recurring_vendors_confirmation_token_uniq')
      .on(table.vendorConfirmationToken)
      .where(sql`${table.vendorConfirmationToken} IS NOT NULL`),
  ],
);

export type RecurringVendor = typeof recurringVendors.$inferSelect;
export type NewRecurringVendor = typeof recurringVendors.$inferInsert;

// ─── vendor_visits ──────────────────────────────────────────────────────────

export const vendorVisits = pgTable(
  'vendor_visits',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    recurringVendorId: uuid('recurring_vendor_id')
      .notNull()
      .references(() => recurringVendors.id, { onDelete: 'cascade' }),
    scheduledAt: timestamp('scheduled_at', { withTimezone: true }).notNull(),
    /** Allowed values: VENDOR_VISIT_STATUSES. Lifecycle:
     *    scheduled → confirmation_sent → confirmed → completed
     *                          ↓
     *                       skipped / missed / disputed (terminal)
     */
    status: text('status').notNull().default('scheduled'),
    confirmationSentAt: timestamp('confirmation_sent_at', { withTimezone: true }),
    confirmedAt: timestamp('confirmed_at', { withTimezone: true }),
    completedAt: timestamp('completed_at', { withTimezone: true }),
    completionPhotoUrl: text('completion_photo_url'),
    completionNotes: text('completion_notes'),
    amountChargedCents: integer('amount_charged_cents'),
    tipCents: integer('tip_cents').notNull().default(0),
    /** Forward link to the vendor_payments row. ON DELETE SET NULL so
     *  refunds (which mark the payment row as 'refunded' but may
     *  optionally also detach) don't cascade-delete the visit history. */
    paymentId: uuid('payment_id'),
    skipReason: text('skip_reason'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index('vendor_visits_vendor_scheduled_idx').on(
      table.recurringVendorId,
      table.scheduledAt.desc(),
    ),
    index('vendor_visits_status_scheduled_idx').on(table.status, table.scheduledAt),
  ],
);

export type VendorVisit = typeof vendorVisits.$inferSelect;
export type NewVendorVisit = typeof vendorVisits.$inferInsert;

// ─── vendor_payments ────────────────────────────────────────────────────────

export const vendorPayments = pgTable(
  'vendor_payments',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    /** Nullable + ON DELETE SET NULL: the corresponding vendor_visit can
     *  be deleted (e.g. cleanup, dispute resolution that removes the
     *  visit) without losing the payment record for accounting/tax. */
    vendorVisitId: uuid('vendor_visit_id').references(() => vendorVisits.id, {
      onDelete: 'set null',
    }),
    recurringVendorId: uuid('recurring_vendor_id')
      .notNull()
      .references(() => recurringVendors.id, { onDelete: 'cascade' }),
    amountCents: integer('amount_cents').notNull(),
    processingFeeCents: integer('processing_fee_cents').notNull().default(0),
    /** Homie's cut from the spread. */
    homieTakeCents: integer('homie_take_cents').notNull().default(0),
    netToVendorCents: integer('net_to_vendor_cents').notNull(),
    /** Allowed values: VENDOR_PAYMENT_METHODS. */
    paymentMethod: text('payment_method').notNull(),
    /** Stripe charge from the member's payment method. Populated in
     *  Session 3 when payment processing lands. */
    stripePaymentIntentId: text('stripe_payment_intent_id'),
    /** Stripe transfer to the vendor's Connect account. Populated in
     *  Session 3 when Connect lands. */
    stripeTransferId: text('stripe_transfer_id'),
    /** Allowed values: VENDOR_PAYMENT_STATUSES. */
    status: text('status').notNull().default('pending'),
    failureReason: text('failure_reason'),
    processedAt: timestamp('processed_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index('vendor_payments_visit_idx').on(table.vendorVisitId),
    index('vendor_payments_vendor_idx').on(table.recurringVendorId),
    index('vendor_payments_status_idx').on(table.status),
  ],
);

export type VendorPayment = typeof vendorPayments.$inferSelect;
export type NewVendorPayment = typeof vendorPayments.$inferInsert;
