import PDFDocument from 'pdfkit';

interface EstimatePDFOptions {
  workspace: {
    name: string;
    logoUrl: string | null;
    companyAddress: string | null;
    companyPhone: string | null;
    companyEmail: string | null;
  };
  property: {
    name: string;
    address: string | null;
    city: string | null;
    state: string | null;
    zipCode: string | null;
  };
  job: {
    id: string;
    status: string;
    createdAt: Date;
    diagnosis: {
      category: string;
      severity: string;
      summary: string;
      confidence?: number;
    } | null;
    preferredTiming: string | null;
    budget: string | null;
  };
  estimates: Array<{
    providerName: string;
    providerPhone?: string | null;
    providerEmail?: string | null;
    providerWebsite?: string | null;
    googleRating: string | null;
    reviewCount: number;
    channel: string;
    isPreferred: boolean;
    quotedPrice: string | null;
    availability: string | null;
    message: string | null;
    responseTimeSec: number | null;
  }>;
  declinedCount: number;
}

const O = '#E8632B';
const D = '#2D2926';
const GRAY = '#6B6560';
const MUTED = '#9B9490';
const WARM = '#F9F5F2';
const BORDER = '#E0DAD4';
const PW = 612;
const PH = 792;
const M = 40;
const CW = PW - M * 2;

function fmtDate(d: Date): string {
  return d.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
}
function fmtTime(sec: number): string {
  if (sec < 60) return `${Math.round(sec)}s`;
  if (sec < 3600) return `${Math.round(sec / 60)} min`;
  const h = Math.floor(sec / 3600);
  const m = Math.round((sec % 3600) / 60);
  return m > 0 ? `${h}h ${m}m` : `${h}h`;
}
function titleCase(s: string): string {
  return s.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
}
function rr(doc: PDFKit.PDFDocument, x: number, y: number, w: number, h: number, r: number) {
  doc.moveTo(x + r, y).lineTo(x + w - r, y).quadraticCurveTo(x + w, y, x + w, y + r)
    .lineTo(x + w, y + h - r).quadraticCurveTo(x + w, y + h, x + w - r, y + h)
    .lineTo(x + r, y + h).quadraticCurveTo(x, y + h, x, y + h - r)
    .lineTo(x, y + r).quadraticCurveTo(x, y, x + r, y).closePath();
}

async function resolveLogoBuffer(url: string): Promise<Buffer | null> {
  try {
    if (url.startsWith('data:image')) {
      const match = url.match(/^data:image\/[^;]+;base64,(.+)$/);
      return match ? Buffer.from(match[1], 'base64') : null;
    }
    if (url.startsWith('http')) {
      const res = await fetch(url);
      return res.ok ? Buffer.from(await res.arrayBuffer()) : null;
    }
    return null;
  } catch { return null; }
}

function drawFooter(doc: PDFKit.PDFDocument, pageNum: number) {
  const fy = PH - 38;
  doc.save().moveTo(M, fy).lineTo(PW - M, fy).lineWidth(0.5).strokeColor(BORDER).stroke().restore();
  doc.font('Helvetica').fontSize(7).fillColor(MUTED);
  doc.text('Generated by Homie — homiepro.ai', M, fy + 5, { width: CW, align: 'left' });
  doc.text(`Page ${pageNum}`, M, fy + 5, { width: CW, align: 'right' });
  doc.fontSize(6);
  doc.text('This estimate summary is for informational purposes only. Actual costs may vary based on on-site assessment.', M, fy + 14, { width: CW, align: 'center' });
}

function checkPage(doc: PDFKit.PDFDocument, y: number, needed: number, pg: { val: number }, ws: EstimatePDFOptions['workspace']): number {
  if (y + needed > PH - 50) {
    drawFooter(doc, pg.val);
    doc.addPage();
    pg.val++;
    let ny = M;
    doc.font('Helvetica-Bold').fontSize(9).fillColor(D).text(ws.name, M, ny, { width: CW / 2 });
    doc.font('Helvetica').fontSize(7).fillColor(MUTED).text('Estimate Summary (cont.)', M + CW / 2, ny, { width: CW / 2, align: 'right' });
    ny += 14;
    doc.save().moveTo(M, ny).lineTo(PW - M, ny).lineWidth(1).strokeColor(O).stroke().restore();
    return ny + 8;
  }
  return y;
}

export async function generateEstimatePDF(options: EstimatePDFOptions): Promise<Buffer> {
  const { workspace, property, job, estimates, declinedCount } = options;
  const doc = new PDFDocument({ size: 'LETTER', margins: { top: M, bottom: 40, left: M, right: M }, bufferPages: true });
  const chunks: Buffer[] = [];
  doc.on('data', (chunk: Buffer) => chunks.push(chunk));

  let logoBuffer: Buffer | null = null;
  if (workspace.logoUrl) logoBuffer = await resolveLogoBuffer(workspace.logoUrl);

  const pg = { val: 1 };
  let y = M;

  // ── HEADER ──────────────────────────────────────────────────────────
  // Right side
  doc.font('Helvetica-Bold').fontSize(12).fillColor(O);
  doc.text('Estimate Summary', M, y, { width: CW, align: 'right' });
  doc.font('Helvetica').fontSize(8).fillColor(GRAY);
  doc.text(`${fmtDate(job.createdAt)}  •  Job #${job.id.substring(0, 8).toUpperCase()}`, M, y + 15, { width: CW, align: 'right' });

  // Left side
  let ly = y;
  if (logoBuffer) {
    try { doc.image(logoBuffer, M, ly, { height: 28 }); ly += 32; } catch { /* skip */ }
  }
  doc.font('Helvetica-Bold').fontSize(13).fillColor(D);
  doc.text(workspace.name, M, ly, { width: CW * 0.55 });
  ly += doc.heightOfString(workspace.name, { width: CW * 0.55 }) + 2;

  // Company details on one line where possible
  const details: string[] = [];
  if (workspace.companyAddress) details.push(workspace.companyAddress);
  if (workspace.companyPhone) details.push(workspace.companyPhone);
  if (workspace.companyEmail) details.push(workspace.companyEmail);
  if (details.length > 0) {
    doc.font('Helvetica').fontSize(7.5).fillColor(MUTED);
    doc.text(details.join('  •  '), M, ly, { width: CW * 0.55 });
    ly += doc.heightOfString(details.join('  •  '), { width: CW * 0.55 }) + 2;
  }

  y = Math.max(ly, y + 32) + 6;
  doc.save().moveTo(M, y).lineTo(PW - M, y).lineWidth(1.5).strokeColor(O).stroke().restore();
  y += 10;

  // ── PROPERTY + JOB (compact, side by side) ──────────────────────────
  const propAddr: string[] = [];
  if (property.address) propAddr.push(property.address);
  const csz: string[] = [];
  if (property.city) csz.push(property.city);
  if (property.state) csz.push(property.state);
  if (property.zipCode) csz.push(property.zipCode);
  if (csz.length > 0) propAddr.push(csz.join(', '));

  doc.font('Helvetica-Bold').fontSize(11).fillColor(D).text(property.name, M, y, { width: CW });
  y += 14;
  if (propAddr.length > 0) {
    doc.font('Helvetica').fontSize(8).fillColor(GRAY).text(propAddr.join(', '), M, y, { width: CW });
    y += 10;
  }
  y += 6;

  // ── JOB SUMMARY BOX (compact) ──────────────────────────────────────
  const diag = job.diagnosis;
  const p = 10;

  // Measure content height
  let bh = 0;
  if (diag) {
    bh += 13; // category line
    const cleanSummary = (diag.summary || '').replace(/\*\*(.+?)\*\*/g, '$1');
    doc.font('Helvetica').fontSize(8.5);
    bh += doc.heightOfString(cleanSummary, { width: CW - p * 2 }) + 4;
    const metaLine: string[] = [`Reported: ${fmtDate(job.createdAt)}`];
    if (diag.confidence) metaLine.push(`Confidence: ${Math.round(diag.confidence * 100)}%`);
    if (job.preferredTiming) metaLine.push(`Timing: ${titleCase(job.preferredTiming)}`);
    if (job.budget) metaLine.push(`Budget: ${job.budget}`);
    bh += 10; // meta line
  } else {
    bh += 13;
  }
  bh += p * 2;

  y = checkPage(doc, y, bh, pg, workspace);
  doc.save(); rr(doc, M, y, CW, bh, 4); doc.fillColor(WARM).fill(); doc.restore();

  let by = y + p;
  if (diag) {
    doc.font('Helvetica-Bold').fontSize(9.5).fillColor(D);
    doc.text(`${titleCase(diag.category)}  •  ${titleCase(diag.severity)}`, M + p, by, { width: CW - p * 2 });
    by += 13;

    const cleanSummary = (diag.summary || '').replace(/\*\*(.+?)\*\*/g, '$1');
    doc.font('Helvetica').fontSize(8.5).fillColor(D);
    const sh = doc.heightOfString(cleanSummary, { width: CW - p * 2 });
    doc.text(cleanSummary, M + p, by, { width: CW - p * 2 });
    by += sh + 4;

    const metaLine: string[] = [`Reported: ${fmtDate(job.createdAt)}`];
    if (diag.confidence) metaLine.push(`Confidence: ${Math.round(diag.confidence * 100)}%`);
    if (job.preferredTiming) metaLine.push(`Timing: ${titleCase(job.preferredTiming)}`);
    if (job.budget) metaLine.push(`Budget: ${job.budget}`);
    doc.font('Helvetica').fontSize(7.5).fillColor(MUTED);
    doc.text(metaLine.join('   •   '), M + p, by, { width: CW - p * 2 });
  } else {
    doc.font('Helvetica-Bold').fontSize(9.5).fillColor(D).text('Service Request', M + p, by, { width: CW - p * 2 });
  }

  y += bh + 12;

  // ── ESTIMATES HEADER ────────────────────────────────────────────────
  y = checkPage(doc, y, 20, pg, workspace);
  doc.font('Helvetica-Bold').fontSize(10).fillColor(D);
  doc.text(`${estimates.length} Estimate${estimates.length !== 1 ? 's' : ''} Received`, M, y, { width: CW * 0.6 });
  if (declinedCount > 0) {
    doc.font('Helvetica').fontSize(7.5).fillColor(MUTED);
    doc.text(`${declinedCount} declined/no response`, M + CW * 0.6, y + 1, { width: CW * 0.4, align: 'right' });
  }
  y += 16;

  // ── ESTIMATE CARDS (compact) ────────────────────────────────────────
  for (const est of estimates) {
    const ip = 10;
    const iw = CW - ip * 2;

    // Calculate height
    let ch = ip; // top
    ch += 14; // name
    // Info line (rating + contact on one line)
    const infoParts: string[] = [];
    if (est.googleRating) infoParts.push(`★ ${est.googleRating}${est.reviewCount > 0 ? ` (${est.reviewCount})` : ''}`);
    if (est.providerPhone) infoParts.push(est.providerPhone);
    if (est.providerEmail) infoParts.push(est.providerEmail);
    if (infoParts.length > 0) ch += 11;
    if (est.providerWebsite) ch += 10;
    ch += 4; // spacing
    if (est.quotedPrice) ch += 18;
    if (est.availability) ch += 12;
    ch += 10; // channel/response line
    if (est.message) {
      doc.font('Helvetica-Oblique').fontSize(8);
      ch += doc.heightOfString(`"${est.message}"`, { width: iw - 12 }) + 10;
    }
    ch += ip; // bottom

    y = checkPage(doc, y, ch + 6, pg, workspace);

    // Card border
    doc.save(); rr(doc, M, y, CW, ch, 4); doc.lineWidth(0.75).strokeColor(BORDER).stroke(); doc.restore();

    let cy = y + ip;

    // Provider name + preferred badge
    doc.font('Helvetica-Bold').fontSize(10).fillColor(D);
    doc.text(est.providerName, M + ip, cy, { width: est.isPreferred ? iw - 60 : iw });
    if (est.isPreferred) {
      const bx = M + CW - ip - 52;
      doc.save(); rr(doc, bx, cy, 44, 13, 3); doc.fillColor(O).fill(); doc.restore();
      doc.font('Helvetica-Bold').fontSize(6).fillColor('#FFF').text('PREFERRED', bx, cy + 3, { width: 44, align: 'center' });
    }
    cy += 14;

    // Info line: rating + phone + email
    if (infoParts.length > 0) {
      doc.font('Helvetica').fontSize(7.5).fillColor(GRAY);
      doc.text(infoParts.join('  •  '), M + ip, cy, { width: iw });
      cy += 11;
    }
    if (est.providerWebsite) {
      doc.font('Helvetica').fontSize(7.5).fillColor(MUTED).text(est.providerWebsite, M + ip, cy, { width: iw });
      cy += 10;
    }
    cy += 4;

    // Quote
    if (est.quotedPrice) {
      doc.font('Helvetica-Bold').fontSize(14).fillColor(O).text(est.quotedPrice, M + ip, cy, { width: iw });
      cy += 18;
    }

    // Availability
    if (est.availability) {
      doc.font('Helvetica').fontSize(8.5).fillColor(D).text(`Availability: ${est.availability}`, M + ip, cy, { width: iw });
      cy += 12;
    }

    // Channel + response time
    doc.font('Helvetica').fontSize(7).fillColor(MUTED);
    const meta: string[] = [`Via ${est.channel.toUpperCase()}`];
    if (est.responseTimeSec !== null) meta.push(`Responded in ${fmtTime(est.responseTimeSec)}`);
    doc.text(meta.join('  •  '), M + ip, cy, { width: iw });
    cy += 10;

    // Message
    if (est.message) {
      doc.save(); rr(doc, M + ip, cy, iw, doc.font('Helvetica-Oblique').fontSize(8).heightOfString(`"${est.message}"`, { width: iw - 12 }) + 8, 3);
      doc.fillColor('#FAFAF8').fill(); doc.restore();
      doc.font('Helvetica-Oblique').fontSize(8).fillColor(GRAY);
      doc.text(`"${est.message}"`, M + ip + 6, cy + 4, { width: iw - 12 });
    }

    y += ch + 6;
  }

  drawFooter(doc, pg.val);
  doc.end();

  return new Promise<Buffer>((resolve, reject) => {
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
  });
}
