import PDFDocument from 'pdfkit';

interface EstimatePDFOptions {
  workspace: {
    name: string;
    logoUrl: string | null;
    companyAddress: string | null;
    companyPhone: string | null;
    companyEmail: string | null;
  };
  property: {
    name: string;
    address: string | null;
    city: string | null;
    state: string | null;
    zipCode: string | null;
  };
  job: {
    id: string;
    status: string;
    createdAt: Date;
    diagnosis: {
      category: string;
      severity: string;
      summary: string;
      confidence?: number;
    } | null;
    preferredTiming: string | null;
    budget: string | null;
  };
  estimates: Array<{
    providerName: string;
    providerPhone?: string | null;
    providerEmail?: string | null;
    providerWebsite?: string | null;
    googleRating: string | null;
    reviewCount: number;
    channel: string;
    isPreferred: boolean;
    quotedPrice: string | null;
    availability: string | null;
    message: string | null;
    responseTimeSec: number | null;
  }>;
  declinedCount: number;
}

const O = '#E8632B';
const D = '#2D2926';
const GRAY = '#6B6560';
const MUTED = '#9B9490';
const WARM = '#F9F5F2';
const BORDER = '#E0DAD4';
const GREEN = '#1B9E77';
const PW = 612;
const PH = 792;
const M = 50;
const CW = PW - M * 2;

function fmtDate(d: Date): string {
  return d.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
}

function fmtTime(sec: number): string {
  if (sec < 60) return `${Math.round(sec)}s`;
  if (sec < 3600) return `${Math.round(sec / 60)} min`;
  const h = Math.floor(sec / 3600);
  const m = Math.round((sec % 3600) / 60);
  return m > 0 ? `${h}h ${m}m` : `${h}h`;
}

function titleCase(s: string): string {
  return s.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
}

function roundedRect(doc: PDFKit.PDFDocument, x: number, y: number, w: number, h: number, r: number) {
  doc.moveTo(x + r, y).lineTo(x + w - r, y)
    .quadraticCurveTo(x + w, y, x + w, y + r).lineTo(x + w, y + h - r)
    .quadraticCurveTo(x + w, y + h, x + w - r, y + h).lineTo(x + r, y + h)
    .quadraticCurveTo(x, y + h, x, y + h - r).lineTo(x, y + r)
    .quadraticCurveTo(x, y, x + r, y).closePath();
}

async function resolveLogoBuffer(url: string): Promise<Buffer | null> {
  try {
    if (url.startsWith('data:image')) {
      const match = url.match(/^data:image\/[^;]+;base64,(.+)$/);
      return match ? Buffer.from(match[1], 'base64') : null;
    }
    if (url.startsWith('http')) {
      const res = await fetch(url);
      if (!res.ok) return null;
      return Buffer.from(await res.arrayBuffer());
    }
    return null;
  } catch { return null; }
}

function drawFooter(doc: PDFKit.PDFDocument, pageNum: number) {
  const fy = PH - 45;
  doc.save().moveTo(M, fy).lineTo(PW - M, fy).lineWidth(0.5).strokeColor(BORDER).stroke().restore();
  doc.font('Helvetica').fontSize(7.5).fillColor(MUTED);
  doc.text('Generated by Homie — homiepro.ai', M, fy + 6, { width: CW, align: 'left' });
  doc.text(`Page ${pageNum}`, M, fy + 6, { width: CW, align: 'right' });
  doc.fontSize(6.5);
  doc.text('This estimate summary is for informational purposes only. Actual costs may vary based on on-site assessment.', M, fy + 17, { width: CW, align: 'center' });
}

function checkPage(doc: PDFKit.PDFDocument, y: number, needed: number, pageNum: { val: number }, workspace: EstimatePDFOptions['workspace'], jobId: string, createdAt: Date): number {
  if (y + needed > PH - 70) {
    drawFooter(doc, pageNum.val);
    doc.addPage();
    pageNum.val++;
    // Small continuation header
    let ny = M;
    doc.font('Helvetica-Bold').fontSize(10).fillColor(D);
    doc.text(workspace.name, M, ny, { width: CW / 2 });
    doc.font('Helvetica').fontSize(8).fillColor(MUTED);
    doc.text('Estimate Summary (cont.)', M + CW / 2, ny, { width: CW / 2, align: 'right' });
    ny += 16;
    doc.save().moveTo(M, ny).lineTo(PW - M, ny).lineWidth(1.5).strokeColor(O).stroke().restore();
    return ny + 12;
  }
  return y;
}

export async function generateEstimatePDF(options: EstimatePDFOptions): Promise<Buffer> {
  const { workspace, property, job, estimates, declinedCount } = options;

  const doc = new PDFDocument({ size: 'LETTER', margins: { top: M, bottom: 60, left: M, right: M }, bufferPages: true });
  const chunks: Buffer[] = [];
  doc.on('data', (chunk: Buffer) => chunks.push(chunk));

  let logoBuffer: Buffer | null = null;
  if (workspace.logoUrl) logoBuffer = await resolveLogoBuffer(workspace.logoUrl);

  const pg = { val: 1 };
  let y = M;

  // ═══════════════════════════════════════════════════════════════════
  // HEADER
  // ═══════════════════════════════════════════════════════════════════

  const headerLeftX = M;
  let logoEndX = M;

  // Logo
  if (logoBuffer) {
    try {
      doc.image(logoBuffer, headerLeftX, y, { height: 40 });
      logoEndX = headerLeftX + 50; // approximate, will be overridden by text position
    } catch { /* skip */ }
  }

  // Company name — position below logo if logo exists, or at top
  const nameY = logoBuffer ? y + 46 : y;
  doc.font('Helvetica-Bold').fontSize(18).fillColor(D);
  doc.text(workspace.name, headerLeftX, nameY, { width: CW * 0.6 });
  let detailY = nameY + 22;

  // Company details stacked below name
  doc.font('Helvetica').fontSize(8.5).fillColor(MUTED);
  if (workspace.companyAddress) {
    doc.text(workspace.companyAddress, headerLeftX, detailY, { width: CW * 0.6 });
    detailY += 11;
  }
  const contactParts: string[] = [];
  if (workspace.companyPhone) contactParts.push(workspace.companyPhone);
  if (workspace.companyEmail) contactParts.push(workspace.companyEmail);
  if (contactParts.length > 0) {
    doc.text(contactParts.join('  •  '), headerLeftX, detailY, { width: CW * 0.6 });
    detailY += 11;
  }

  // Right side: Estimate Summary title + date + job ID
  const rightX = M + CW * 0.55;
  const rightW = CW * 0.45;
  doc.font('Helvetica-Bold').fontSize(15).fillColor(O);
  doc.text('Estimate Summary', rightX, y, { width: rightW, align: 'right' });
  doc.font('Helvetica').fontSize(9).fillColor(GRAY);
  doc.text(fmtDate(job.createdAt), rightX, y + 20, { width: rightW, align: 'right' });
  doc.text(`Job #${job.id.substring(0, 8).toUpperCase()}`, rightX, y + 32, { width: rightW, align: 'right' });

  y = Math.max(detailY, y + 48) + 8;

  // Orange divider
  doc.save().moveTo(M, y).lineTo(PW - M, y).lineWidth(2).strokeColor(O).stroke().restore();
  y += 16;

  // ═══════════════════════════════════════════════════════════════════
  // PROPERTY
  // ═══════════════════════════════════════════════════════════════════

  doc.font('Helvetica-Bold').fontSize(13).fillColor(D);
  doc.text(property.name, M, y, { width: CW });
  y += 18;

  const addrParts: string[] = [];
  if (property.address) addrParts.push(property.address);
  const csz: string[] = [];
  if (property.city) csz.push(property.city);
  if (property.state) csz.push(property.state);
  if (property.zipCode) csz.push(property.zipCode);
  if (csz.length > 0) addrParts.push(csz.join(', '));
  if (addrParts.length > 0) {
    doc.font('Helvetica').fontSize(9.5).fillColor(GRAY);
    doc.text(addrParts.join(', '), M, y, { width: CW });
    y += 14;
  }
  y += 10;

  // ═══════════════════════════════════════════════════════════════════
  // JOB SUMMARY BOX
  // ═══════════════════════════════════════════════════════════════════

  const diag = job.diagnosis;
  const pad = 16;

  // Calculate box height dynamically
  let tempY = 0;
  tempY += 18; // title
  if (diag) {
    tempY += 14; // category + severity
    tempY += 12; // date
    tempY += 8; // spacing
    const summaryClean = (diag.summary || '').replace(/\*\*(.+?)\*\*/g, '$1');
    const summaryH = doc.font('Helvetica').fontSize(9.5).heightOfString(summaryClean, { width: CW - pad * 2 });
    tempY += summaryH + 6;
    if (diag.confidence) tempY += 12;
  }
  if (job.preferredTiming || job.budget) tempY += 14;
  const boxH = tempY + pad * 2;

  y = checkPage(doc, y, boxH, pg, workspace, job.id, job.createdAt);

  doc.save();
  roundedRect(doc, M, y, CW, boxH, 6);
  doc.fillColor(WARM).fill();
  doc.restore();

  let by = y + pad;

  if (diag) {
    doc.font('Helvetica-Bold').fontSize(12).fillColor(D);
    doc.text(titleCase(diag.category), M + pad, by, { width: CW - pad * 2 });
    by += 18;

    doc.font('Helvetica').fontSize(9).fillColor(GRAY);
    doc.text(`Severity: ${titleCase(diag.severity)}  •  Reported: ${fmtDate(job.createdAt)}`, M + pad, by, { width: CW - pad * 2 });
    by += 14;
    by += 6;

    const summaryClean = (diag.summary || '').replace(/\*\*(.+?)\*\*/g, '$1');
    doc.font('Helvetica').fontSize(9.5).fillColor(D);
    const sH = doc.heightOfString(summaryClean, { width: CW - pad * 2 });
    doc.text(summaryClean, M + pad, by, { width: CW - pad * 2 });
    by += sH + 6;

    if (diag.confidence) {
      doc.font('Helvetica').fontSize(8.5).fillColor(MUTED);
      doc.text(`AI Diagnostic Confidence: ${Math.round(diag.confidence * 100)}%`, M + pad, by, { width: CW - pad * 2 });
      by += 12;
    }
  } else {
    doc.font('Helvetica-Bold').fontSize(12).fillColor(D);
    doc.text('Service Request', M + pad, by, { width: CW - pad * 2 });
    by += 18;
  }

  if (job.preferredTiming || job.budget) {
    const parts: string[] = [];
    if (job.preferredTiming) parts.push(`Timing: ${titleCase(job.preferredTiming)}`);
    if (job.budget) parts.push(`Budget: ${job.budget}`);
    doc.font('Helvetica').fontSize(9).fillColor(GRAY);
    doc.text(parts.join('    •    '), M + pad, by, { width: CW - pad * 2 });
    by += 14;
  }

  y += boxH + 20;

  // ═══════════════════════════════════════════════════════════════════
  // ESTIMATES HEADER
  // ═══════════════════════════════════════════════════════════════════

  y = checkPage(doc, y, 30, pg, workspace, job.id, job.createdAt);

  doc.font('Helvetica-Bold').fontSize(13).fillColor(D);
  doc.text(`${estimates.length} Estimate${estimates.length !== 1 ? 's' : ''} Received`, M, y, { width: CW });
  y += 18;

  if (declinedCount > 0) {
    doc.font('Helvetica').fontSize(8.5).fillColor(MUTED);
    doc.text(`${declinedCount} additional provider${declinedCount !== 1 ? 's were' : ' was'} contacted but declined or did not respond.`, M, y, { width: CW });
    y += 14;
  }
  y += 8;

  // ═══════════════════════════════════════════════════════════════════
  // ESTIMATE CARDS
  // ═══════════════════════════════════════════════════════════════════

  for (let i = 0; i < estimates.length; i++) {
    const est = estimates[i];
    const ip = 14; // inner padding

    // Pre-calculate card height
    let cardH = ip; // top padding
    cardH += 16; // provider name row
    cardH += 4; // spacing

    // Info rows
    const infoRows: string[] = [];
    if (est.googleRating) infoRows.push(`★ ${est.googleRating}${est.reviewCount > 0 ? ` (${est.reviewCount} reviews)` : ''} — Google`);
    if (est.providerPhone) infoRows.push(`Phone: ${est.providerPhone}`);
    if (est.providerEmail) infoRows.push(`Email: ${est.providerEmail}`);
    if (est.providerWebsite) infoRows.push(`Web: ${est.providerWebsite}`);
    cardH += infoRows.length * 13;
    if (infoRows.length > 0) cardH += 6; // spacing after info

    // Quote + availability row
    if (est.quotedPrice || est.availability) {
      cardH += 22; // quote row
      cardH += 6;
    }

    // Channel + response time row
    cardH += 12;

    // Message
    if (est.message) {
      const msgH = doc.font('Helvetica-Oblique').fontSize(9).heightOfString(`"${est.message}"`, { width: CW - ip * 2 });
      cardH += msgH + 8;
    }

    cardH += ip; // bottom padding

    y = checkPage(doc, y, cardH + 8, pg, workspace, job.id, job.createdAt);

    // Card background
    doc.save();
    roundedRect(doc, M, y, CW, cardH, 6);
    doc.lineWidth(1).strokeColor(BORDER).stroke();
    doc.restore();

    let cy = y + ip;
    const iw = CW - ip * 2;

    // ── Provider name row ──
    doc.font('Helvetica-Bold').fontSize(12).fillColor(D);
    const nameW = est.isPreferred ? iw - 75 : iw;
    doc.text(est.providerName, M + ip, cy, { width: nameW });

    // Preferred badge
    if (est.isPreferred) {
      const bx = M + CW - ip - 68;
      doc.save();
      roundedRect(doc, bx, cy, 58, 16, 4);
      doc.fillColor(O).fill();
      doc.restore();
      doc.font('Helvetica-Bold').fontSize(7).fillColor('#FFFFFF');
      doc.text('PREFERRED', bx + 2, cy + 4, { width: 54, align: 'center' });
    }
    cy += 16 + 4;

    // ── Info rows (rating, phone, email, website) ──
    doc.font('Helvetica').fontSize(9).fillColor(GRAY);
    for (const row of infoRows) {
      doc.text(row, M + ip, cy, { width: iw });
      cy += 13;
    }
    if (infoRows.length > 0) cy += 4;

    // ── Quote + Availability row ──
    if (est.quotedPrice || est.availability) {
      const qx = M + ip;
      if (est.quotedPrice) {
        doc.font('Helvetica-Bold').fontSize(16).fillColor(O);
        doc.text(est.quotedPrice, qx, cy, { continued: false });
        // Availability next to price
        if (est.availability) {
          doc.font('Helvetica').fontSize(9.5).fillColor(D);
          const priceW = doc.widthOfString(est.quotedPrice);
          doc.text(`  •  ${est.availability}`, qx + priceW + 4, cy + 4, { width: iw - priceW - 10 });
        }
      } else if (est.availability) {
        doc.font('Helvetica').fontSize(10).fillColor(D);
        doc.text(`Availability: ${est.availability}`, qx, cy, { width: iw });
      }
      cy += 22 + 4;
    }

    // ── Channel + response time ──
    doc.font('Helvetica').fontSize(8).fillColor(MUTED);
    const metaParts: string[] = [`Contacted via ${est.channel.toUpperCase()}`];
    if (est.responseTimeSec !== null) metaParts.push(`Responded in ${fmtTime(est.responseTimeSec)}`);
    doc.text(metaParts.join('  •  '), M + ip, cy, { width: iw });
    cy += 12;

    // ── Provider message ──
    if (est.message) {
      cy += 2;
      doc.save();
      // Light background for the note
      const noteH = doc.font('Helvetica-Oblique').fontSize(9).heightOfString(`"${est.message}"`, { width: iw - 16 }) + 12;
      roundedRect(doc, M + ip, cy, iw, noteH, 4);
      doc.fillColor('#FAFAF8').fill();
      doc.restore();

      doc.font('Helvetica-Oblique').fontSize(9).fillColor(GRAY);
      doc.text(`"${est.message}"`, M + ip + 8, cy + 6, { width: iw - 16 });
    }

    y += cardH + 10;
  }

  // ═══════════════════════════════════════════════════════════════════
  // FOOTER
  // ═══════════════════════════════════════════════════════════════════

  drawFooter(doc, pg.val);
  doc.end();

  return new Promise<Buffer>((resolve, reject) => {
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
  });
}
