import { db } from '../index';
import { scheduleTemplates } from '../schema/schedules';

interface TemplateRow {
  category: string;
  title: string;
  description: string;
  suggestedCadenceType: string;
  suggestedCadenceConfig: Record<string, unknown> | null;
  propertyTypes: string[] | null;
  climateZones: string[] | null;
  amenityTags: string[] | null;
  estimatedCostRange: string;
  whyItMatters: string;
  seasonalRelevance: string[] | null;
  sortPriority: number;
  isSystem: boolean;
  source: string;
}

const TEMPLATES: TemplateRow[] = [
  // ── Cleaning (5) ──────────────────────────────────────────────────────────
  {
    category: 'cleaning',
    title: 'Deep Clean — Full Property',
    description: 'Comprehensive deep cleaning of entire property including all rooms, bathrooms, kitchen, and common areas.',
    suggestedCadenceType: 'monthly',
    suggestedCadenceConfig: null,
    propertyTypes: ['short_term_rental', 'residential', 'vacation'],
    climateZones: null,
    amenityTags: null,
    estimatedCostRange: '$150–$400',
    whyItMatters: 'Regular deep cleaning prevents build-up, maintains guest satisfaction, and extends the life of finishes and fixtures.',
    seasonalRelevance: null,
    sortPriority: 10,
    isSystem: true,
    source: 'system',
  },
  {
    category: 'cleaning',
    title: 'Turnover Clean',
    description: 'Quick turnover clean between guest stays including linens, trash, restocking supplies, and surface sanitization.',
    suggestedCadenceType: 'per_event',
    suggestedCadenceConfig: null,
    propertyTypes: ['short_term_rental', 'vacation'],
    climateZones: null,
    amenityTags: null,
    estimatedCostRange: '$75–$200',
    whyItMatters: 'Consistent turnover cleaning is the #1 factor in positive guest reviews and repeat bookings.',
    seasonalRelevance: null,
    sortPriority: 5,
    isSystem: true,
    source: 'system',
  },
  {
    category: 'cleaning',
    title: 'Carpet & Upholstery Cleaning',
    description: 'Professional steam cleaning of carpets, rugs, and upholstered furniture to remove deep stains and allergens.',
    suggestedCadenceType: 'quarterly',
    suggestedCadenceConfig: null,
    propertyTypes: ['short_term_rental', 'residential', 'vacation'],
    climateZones: null,
    amenityTags: null,
    estimatedCostRange: '$200–$500',
    whyItMatters: 'Extends carpet life by 3–5 years and removes allergens that accumulate between surface cleanings.',
    seasonalRelevance: null,
    sortPriority: 30,
    isSystem: true,
    source: 'system',
  },
  {
    category: 'cleaning',
    title: 'Window Cleaning — Interior & Exterior',
    description: 'Professional cleaning of all windows, screens, and tracks, both interior and exterior surfaces.',
    suggestedCadenceType: 'semi_annual',
    suggestedCadenceConfig: null,
    propertyTypes: ['short_term_rental', 'residential', 'vacation'],
    climateZones: null,
    amenityTags: null,
    estimatedCostRange: '$150–$350',
    whyItMatters: 'Clean windows improve curb appeal and natural lighting. Mineral deposits can permanently etch glass if left too long.',
    seasonalRelevance: ['spring', 'fall'],
    sortPriority: 40,
    isSystem: true,
    source: 'system',
  },
  {
    category: 'cleaning',
    title: 'Pressure Washing — Exterior',
    description: 'Power wash driveways, walkways, patios, siding, and decks to remove mold, mildew, and grime.',
    suggestedCadenceType: 'semi_annual',
    suggestedCadenceConfig: null,
    propertyTypes: ['short_term_rental', 'residential', 'vacation'],
    climateZones: ['humid_subtropical', 'tropical', 'marine'],
    amenityTags: ['patio', 'deck', 'driveway'],
    estimatedCostRange: '$200–$500',
    whyItMatters: 'Prevents mold and mildew damage, maintains property value, and reduces slip hazards on walkways.',
    seasonalRelevance: ['spring', 'fall'],
    sortPriority: 35,
    isSystem: true,
    source: 'system',
  },

  // ── Outdoor / Landscaping (5) ─────────────────────────────────────────────
  {
    category: 'outdoor',
    title: 'Lawn Mowing & Edging',
    description: 'Regular lawn mowing, edging along walkways and beds, and blowing of clippings from hard surfaces.',
    suggestedCadenceType: 'weekly',
    suggestedCadenceConfig: null,
    propertyTypes: ['short_term_rental', 'residential', 'vacation'],
    climateZones: null,
    amenityTags: ['yard', 'lawn'],
    estimatedCostRange: '$30–$80',
    whyItMatters: 'Overgrown lawns attract pests, lower property appeal, and may violate HOA or city codes.',
    seasonalRelevance: ['spring', 'summer', 'fall'],
    sortPriority: 10,
    isSystem: true,
    source: 'system',
  },
  {
    category: 'outdoor',
    title: 'Tree & Hedge Trimming',
    description: 'Trim overhanging branches, shape hedges, and remove dead limbs to maintain clearance and aesthetics.',
    suggestedCadenceType: 'quarterly',
    suggestedCadenceConfig: null,
    propertyTypes: ['short_term_rental', 'residential', 'vacation'],
    climateZones: null,
    amenityTags: ['trees', 'hedges'],
    estimatedCostRange: '$150–$500',
    whyItMatters: 'Prevents roof and gutter damage from overhanging limbs, reduces storm hazards, and maintains sight lines.',
    seasonalRelevance: ['spring', 'fall'],
    sortPriority: 25,
    isSystem: true,
    source: 'system',
  },
  {
    category: 'outdoor',
    title: 'Irrigation System Check',
    description: 'Inspect sprinkler heads, check for leaks, adjust coverage zones, and verify timer programming.',
    suggestedCadenceType: 'monthly',
    suggestedCadenceConfig: null,
    propertyTypes: ['short_term_rental', 'residential', 'vacation'],
    climateZones: ['arid', 'semi_arid', 'humid_subtropical'],
    amenityTags: ['irrigation', 'sprinklers'],
    estimatedCostRange: '$50–$120',
    whyItMatters: 'A single broken sprinkler head can waste 25,000+ gallons per month and cause foundation damage.',
    seasonalRelevance: ['spring', 'summer'],
    sortPriority: 20,
    isSystem: true,
    source: 'system',
  },
  {
    category: 'outdoor',
    title: 'Gutter Cleaning',
    description: 'Remove debris from gutters and downspouts, flush with water, and check for proper drainage.',
    suggestedCadenceType: 'semi_annual',
    suggestedCadenceConfig: null,
    propertyTypes: ['short_term_rental', 'residential', 'vacation'],
    climateZones: null,
    amenityTags: null,
    estimatedCostRange: '$100–$250',
    whyItMatters: 'Clogged gutters cause water intrusion, foundation erosion, and can lead to thousands in water damage.',
    seasonalRelevance: ['spring', 'fall'],
    sortPriority: 15,
    isSystem: true,
    source: 'system',
  },
  {
    category: 'outdoor',
    title: 'Seasonal Flower & Mulch Refresh',
    description: 'Replace seasonal flowers in beds, refresh mulch, and pull weeds from landscaped areas.',
    suggestedCadenceType: 'quarterly',
    suggestedCadenceConfig: null,
    propertyTypes: ['short_term_rental', 'residential', 'vacation'],
    climateZones: null,
    amenityTags: ['garden', 'flower_beds'],
    estimatedCostRange: '$100–$300',
    whyItMatters: 'Fresh landscaping boosts curb appeal — studies show it increases perceived property value by 5–12%.',
    seasonalRelevance: ['spring', 'summer', 'fall'],
    sortPriority: 35,
    isSystem: true,
    source: 'system',
  },

  // ── Pool (3) ──────────────────────────────────────────────────────────────
  {
    category: 'pool',
    title: 'Weekly Pool Maintenance',
    description: 'Test and balance chemicals, skim surface, vacuum floor, clean skimmer baskets, and backwash filter.',
    suggestedCadenceType: 'weekly',
    suggestedCadenceConfig: null,
    propertyTypes: ['short_term_rental', 'residential', 'vacation'],
    climateZones: null,
    amenityTags: ['pool'],
    estimatedCostRange: '$80–$150',
    whyItMatters: 'Unbalanced pool chemistry can cause algae within 48 hours and damage equipment worth thousands.',
    seasonalRelevance: ['spring', 'summer', 'fall'],
    sortPriority: 10,
    isSystem: true,
    source: 'system',
  },
  {
    category: 'pool',
    title: 'Pool Equipment Inspection',
    description: 'Inspect pump, filter, heater, salt cell, and automation system. Check for leaks and unusual noise.',
    suggestedCadenceType: 'monthly',
    suggestedCadenceConfig: null,
    propertyTypes: ['short_term_rental', 'residential', 'vacation'],
    climateZones: null,
    amenityTags: ['pool'],
    estimatedCostRange: '$100–$200',
    whyItMatters: 'Catching a failing pump seal early saves $500+ compared to emergency replacement after burnout.',
    seasonalRelevance: null,
    sortPriority: 20,
    isSystem: true,
    source: 'system',
  },
  {
    category: 'pool',
    title: 'Pool Opening / Closing (Seasonal)',
    description: 'Seasonal opening or winterization of pool including cover removal/installation, chemical treatment, and equipment startup/shutdown.',
    suggestedCadenceType: 'semi_annual',
    suggestedCadenceConfig: null,
    propertyTypes: ['short_term_rental', 'residential', 'vacation'],
    climateZones: ['continental', 'humid_continental', 'subarctic'],
    amenityTags: ['pool'],
    estimatedCostRange: '$250–$500',
    whyItMatters: 'Improper winterization is the leading cause of cracked pipes and equipment failure in pools.',
    seasonalRelevance: ['spring', 'fall'],
    sortPriority: 15,
    isSystem: true,
    source: 'system',
  },

  // ── HVAC (4) ──────────────────────────────────────────────────────────────
  {
    category: 'hvac',
    title: 'HVAC Filter Replacement',
    description: 'Replace air filters in all HVAC units. Check filter size, install new filters, and note condition of old ones.',
    suggestedCadenceType: 'monthly',
    suggestedCadenceConfig: null,
    propertyTypes: ['short_term_rental', 'residential', 'vacation'],
    climateZones: null,
    amenityTags: null,
    estimatedCostRange: '$15–$50',
    whyItMatters: 'Dirty filters reduce efficiency by 5–15%, increase energy costs, and accelerate equipment wear.',
    seasonalRelevance: null,
    sortPriority: 5,
    isSystem: true,
    source: 'system',
  },
  {
    category: 'hvac',
    title: 'AC Tune-Up (Pre-Summer)',
    description: 'Professional AC inspection: refrigerant levels, coil cleaning, electrical connections, thermostat calibration, and drain line flush.',
    suggestedCadenceType: 'annual',
    suggestedCadenceConfig: null,
    propertyTypes: ['short_term_rental', 'residential', 'vacation'],
    climateZones: null,
    amenityTags: null,
    estimatedCostRange: '$80–$200',
    whyItMatters: 'Annual tune-ups extend system life by 5+ years and prevent mid-summer breakdowns when technicians are scarce.',
    seasonalRelevance: ['spring'],
    sortPriority: 10,
    isSystem: true,
    source: 'system',
  },
  {
    category: 'hvac',
    title: 'Furnace / Heating Tune-Up (Pre-Winter)',
    description: 'Professional heating inspection: heat exchanger check, burner cleaning, safety controls test, and carbon monoxide screening.',
    suggestedCadenceType: 'annual',
    suggestedCadenceConfig: null,
    propertyTypes: ['short_term_rental', 'residential', 'vacation'],
    climateZones: ['continental', 'humid_continental', 'subarctic', 'semi_arid'],
    amenityTags: null,
    estimatedCostRange: '$80–$200',
    whyItMatters: 'Cracked heat exchangers are a carbon monoxide risk. Pre-season checks catch problems before cold snaps.',
    seasonalRelevance: ['fall'],
    sortPriority: 10,
    isSystem: true,
    source: 'system',
  },
  {
    category: 'hvac',
    title: 'Duct Cleaning',
    description: 'Professional cleaning of supply and return air ducts, registers, grilles, and HVAC coils to remove dust and contaminants.',
    suggestedCadenceType: 'annual',
    suggestedCadenceConfig: null,
    propertyTypes: ['short_term_rental', 'residential', 'vacation'],
    climateZones: null,
    amenityTags: null,
    estimatedCostRange: '$300–$600',
    whyItMatters: 'Dirty ducts circulate allergens and pet dander, a top complaint in guest reviews for rental properties.',
    seasonalRelevance: ['spring'],
    sortPriority: 30,
    isSystem: true,
    source: 'system',
  },

  // ── Pest Control (3) ──────────────────────────────────────────────────────
  {
    category: 'pest',
    title: 'General Pest Treatment — Interior & Exterior',
    description: 'Perimeter spray, interior crack & crevice treatment, bait stations, and inspection for activity.',
    suggestedCadenceType: 'quarterly',
    suggestedCadenceConfig: null,
    propertyTypes: ['short_term_rental', 'residential', 'vacation'],
    climateZones: null,
    amenityTags: null,
    estimatedCostRange: '$80–$150',
    whyItMatters: 'Quarterly treatments keep pest populations below threshold. Reactive calls cost 3x more than preventive plans.',
    seasonalRelevance: null,
    sortPriority: 10,
    isSystem: true,
    source: 'system',
  },
  {
    category: 'pest',
    title: 'Termite Inspection',
    description: 'Annual inspection for termite activity including subterranean, drywood, and dampwood species. Check foundation, crawlspace, and attic.',
    suggestedCadenceType: 'annual',
    suggestedCadenceConfig: null,
    propertyTypes: ['short_term_rental', 'residential', 'vacation'],
    climateZones: ['humid_subtropical', 'tropical', 'marine'],
    amenityTags: null,
    estimatedCostRange: '$75–$150',
    whyItMatters: 'Termites cause $5B in US property damage annually. Early detection saves an average of $3,000 in repairs.',
    seasonalRelevance: ['spring'],
    sortPriority: 15,
    isSystem: true,
    source: 'system',
  },
  {
    category: 'pest',
    title: 'Mosquito / Tick Yard Treatment',
    description: 'Barrier spray treatment of yard, shrubs, and standing water areas to reduce mosquito and tick populations.',
    suggestedCadenceType: 'monthly',
    suggestedCadenceConfig: null,
    propertyTypes: ['short_term_rental', 'residential', 'vacation'],
    climateZones: ['humid_subtropical', 'tropical', 'humid_continental'],
    amenityTags: ['yard', 'outdoor_living'],
    estimatedCostRange: '$60–$120',
    whyItMatters: 'Mosquito complaints are a top-3 reason for negative outdoor experience reviews at rental properties.',
    seasonalRelevance: ['spring', 'summer'],
    sortPriority: 25,
    isSystem: true,
    source: 'system',
  },

  // ── Safety (5) ────────────────────────────────────────────────────────────
  {
    category: 'safety',
    title: 'Smoke & CO Detector Testing',
    description: 'Test all smoke and carbon monoxide detectors, replace batteries, and verify proper placement per code.',
    suggestedCadenceType: 'semi_annual',
    suggestedCadenceConfig: null,
    propertyTypes: ['short_term_rental', 'residential', 'vacation'],
    climateZones: null,
    amenityTags: null,
    estimatedCostRange: '$0–$50',
    whyItMatters: 'Required by law in all 50 states for rentals. Non-functioning detectors create massive liability exposure.',
    seasonalRelevance: ['spring', 'fall'],
    sortPriority: 5,
    isSystem: true,
    source: 'system',
  },
  {
    category: 'safety',
    title: 'Fire Extinguisher Inspection',
    description: 'Inspect all fire extinguishers for charge level, expiration, accessibility, and signage. Recharge or replace as needed.',
    suggestedCadenceType: 'annual',
    suggestedCadenceConfig: null,
    propertyTypes: ['short_term_rental', 'residential', 'vacation'],
    climateZones: null,
    amenityTags: null,
    estimatedCostRange: '$20–$75',
    whyItMatters: 'Many jurisdictions require annual certification for rental properties. Expired extinguishers may not function in emergencies.',
    seasonalRelevance: null,
    sortPriority: 15,
    isSystem: true,
    source: 'system',
  },
  {
    category: 'safety',
    title: 'Dryer Vent Cleaning',
    description: 'Clean lint from dryer vent duct, exterior hood, and transition hose. Check airflow and duct condition.',
    suggestedCadenceType: 'annual',
    suggestedCadenceConfig: null,
    propertyTypes: ['short_term_rental', 'residential', 'vacation'],
    climateZones: null,
    amenityTags: ['laundry'],
    estimatedCostRange: '$100–$200',
    whyItMatters: 'Lint-clogged dryer vents cause 15,000+ house fires per year. High-turnover rentals accumulate lint 3x faster.',
    seasonalRelevance: null,
    sortPriority: 10,
    isSystem: true,
    source: 'system',
  },
  {
    category: 'safety',
    title: 'Water Heater Flush & Inspection',
    description: 'Drain and flush tank to remove sediment, test T&P relief valve, check anode rod, and inspect for leaks.',
    suggestedCadenceType: 'annual',
    suggestedCadenceConfig: null,
    propertyTypes: ['short_term_rental', 'residential', 'vacation'],
    climateZones: null,
    amenityTags: null,
    estimatedCostRange: '$100–$200',
    whyItMatters: 'Sediment buildup reduces efficiency 20–40% and shortens tank life. Failing T&P valves can cause explosions.',
    seasonalRelevance: ['fall'],
    sortPriority: 20,
    isSystem: true,
    source: 'system',
  },
  {
    category: 'safety',
    title: 'Electrical Panel Inspection',
    description: 'Licensed electrician inspects breaker panel, tests GFCI/AFCI outlets, checks for code violations, and verifies grounding.',
    suggestedCadenceType: 'annual',
    suggestedCadenceConfig: null,
    propertyTypes: ['short_term_rental', 'residential', 'vacation'],
    climateZones: null,
    amenityTags: null,
    estimatedCostRange: '$150–$300',
    whyItMatters: 'Electrical faults cause 50,000+ home fires per year. Rental properties require code-compliant electrical systems.',
    seasonalRelevance: null,
    sortPriority: 25,
    isSystem: true,
    source: 'system',
  },

  // ── Supplies (3) ──────────────────────────────────────────────────────────
  {
    category: 'supplies',
    title: 'Consumable Restocking',
    description: 'Restock toilet paper, paper towels, soap, shampoo, coffee, trash bags, and other guest consumables.',
    suggestedCadenceType: 'per_event',
    suggestedCadenceConfig: null,
    propertyTypes: ['short_term_rental', 'vacation'],
    climateZones: null,
    amenityTags: null,
    estimatedCostRange: '$30–$100',
    whyItMatters: 'Running out of essentials is the #1 preventable complaint in short-term rental guest reviews.',
    seasonalRelevance: null,
    sortPriority: 5,
    isSystem: true,
    source: 'system',
  },
  {
    category: 'supplies',
    title: 'Linen Inspection & Replacement',
    description: 'Inspect all sheets, towels, pillows, and mattress protectors. Replace worn or stained items.',
    suggestedCadenceType: 'quarterly',
    suggestedCadenceConfig: null,
    propertyTypes: ['short_term_rental', 'vacation'],
    climateZones: null,
    amenityTags: null,
    estimatedCostRange: '$100–$400',
    whyItMatters: 'Stained or worn linens are immediately visible in reviews. Proactive replacement prevents negative impressions.',
    seasonalRelevance: null,
    sortPriority: 15,
    isSystem: true,
    source: 'system',
  },
  {
    category: 'supplies',
    title: 'Welcome Kit & Amenity Refresh',
    description: 'Refresh welcome basket items, local guides, streaming login cards, and seasonal amenities (sunscreen, bug spray, etc.).',
    suggestedCadenceType: 'quarterly',
    suggestedCadenceConfig: null,
    propertyTypes: ['short_term_rental', 'vacation'],
    climateZones: null,
    amenityTags: null,
    estimatedCostRange: '$25–$75',
    whyItMatters: 'Thoughtful touches drive 5-star reviews and justify premium nightly rates.',
    seasonalRelevance: ['spring', 'summer', 'fall', 'winter'],
    sortPriority: 30,
    isSystem: true,
    source: 'system',
  },

  // ── Trash / Waste (2) ─────────────────────────────────────────────────────
  {
    category: 'trash',
    title: 'Trash & Recycling Bin Management',
    description: 'Roll bins to curb on collection days, return bins after pickup, and clean bins monthly.',
    suggestedCadenceType: 'weekly',
    suggestedCadenceConfig: null,
    propertyTypes: ['short_term_rental', 'vacation'],
    climateZones: null,
    amenityTags: null,
    estimatedCostRange: '$15–$40',
    whyItMatters: 'Missed trash pickup leads to overflowing bins, pest attraction, and HOA fines at vacation rentals.',
    seasonalRelevance: null,
    sortPriority: 10,
    isSystem: true,
    source: 'system',
  },
  {
    category: 'trash',
    title: 'Bulk Junk Removal',
    description: 'Schedule pickup of large items, old furniture, mattresses, and accumulated junk that does not fit in regular bins.',
    suggestedCadenceType: 'semi_annual',
    suggestedCadenceConfig: null,
    propertyTypes: ['short_term_rental', 'residential', 'vacation'],
    climateZones: null,
    amenityTags: null,
    estimatedCostRange: '$100–$400',
    whyItMatters: 'Accumulated junk creates pest harborage, fire hazards, and reduces usable space in garages and storage areas.',
    seasonalRelevance: ['spring', 'fall'],
    sortPriority: 35,
    isSystem: true,
    source: 'system',
  },
];

export async function seedScheduleTemplates(): Promise<void> {
  // Upsert based on title to be idempotent
  for (const t of TEMPLATES) {
    await db
      .insert(scheduleTemplates)
      .values(t)
      .onConflictDoNothing();
  }
  console.log(`Seeded ${TEMPLATES.length} schedule templates`);
}
